import Head from "next/head";
import Button from "@mui/material/Button";
import ResponsiveDrawer from "../components/Drawer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ChatMatik Web App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <ResponsiveDrawer />
    </div>
  );
}
